spring:
  devtools:
    livereload:
      port: 35792
      enabled: true
    restart:
      enabled: true
  application:
    name: sharding-jdbc-demo
  main:
    allow-bean-definition-overriding: true
  profiles:
#    # 基本的分库分表
#    active: sharding
    # 读写分离
    active: rwsplit
  shardingsphere:
    props:
      sql:
        show: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: cn.dox.jdbcdemo.model
  global-config:
    field-strategy: 0
    db-column-underline: true
    id-type: 0
  mapper-locations: classpath:mapper/*.xml

