spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.97.166.150:3306/sharding-j0
        username: root
        password: mysql-pw
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        drive-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.97.166.150:3306/sharding-j1
        username: root
        password: mysql-pw
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}
      tables:
        user:
          actual-data-nodes: ds$->{0..1}.user
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user


