spring:
  devtools:
    livereload:
      port: 35792
      enabled: true
    restart:
      enabled: true
  application:
    name: sharding-jdbc-demo
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.97.166.150:3306/sharding-j0
        username: root
        password: mysql-pw
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        drive-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.97.166.150:3306/sharding-j1
        username: root
        password: mysql-pw
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}
      tables:
        user:
          actual-data-nodes: ds$->{0..1}.user
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user
  main:
    allow-bean-definition-overriding: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: cn.dox.jdbcdemo.model
  global-config:
    field-strategy: 0
    db-column-underline: true
    id-type: 0
  mapper-locations: classpath:mapper/*.xml

